// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.2
// source: ipc_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendStunAddrRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid  string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`    //要发往的设备的uid
	Ip   string `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`      //获取到的公网ip
	Port int32  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"` //获取到的公网port
}

func (x *SendStunAddrRequest) Reset() {
	*x = SendStunAddrRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ipc_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendStunAddrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendStunAddrRequest) ProtoMessage() {}

func (x *SendStunAddrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendStunAddrRequest.ProtoReflect.Descriptor instead.
func (*SendStunAddrRequest) Descriptor() ([]byte, []int) {
	return file_ipc_service_proto_rawDescGZIP(), []int{0}
}

func (x *SendStunAddrRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *SendStunAddrRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *SendStunAddrRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type SendStunAddrReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	IpcIp   string `protobuf:"bytes,2,opt,name=ipcIp,proto3" json:"ipcIp,omitempty"`
	IpcPort int32  `protobuf:"varint,3,opt,name=ipcPort,proto3" json:"ipcPort,omitempty"`
}

func (x *SendStunAddrReply) Reset() {
	*x = SendStunAddrReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ipc_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendStunAddrReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendStunAddrReply) ProtoMessage() {}

func (x *SendStunAddrReply) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendStunAddrReply.ProtoReflect.Descriptor instead.
func (*SendStunAddrReply) Descriptor() ([]byte, []int) {
	return file_ipc_service_proto_rawDescGZIP(), []int{1}
}

func (x *SendStunAddrReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendStunAddrReply) GetIpcIp() string {
	if x != nil {
		return x.IpcIp
	}
	return ""
}

func (x *SendStunAddrReply) GetIpcPort() int32 {
	if x != nil {
		return x.IpcPort
	}
	return 0
}

var File_ipc_service_proto protoreflect.FileDescriptor

var file_ipc_service_proto_rawDesc = []byte{
	0x0a, 0x11, 0x69, 0x70, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x4b, 0x0a, 0x13,
	0x53, 0x65, 0x6e, 0x64, 0x53, 0x74, 0x75, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x5d, 0x0a, 0x11, 0x53, 0x65, 0x6e,
	0x64, 0x53, 0x74, 0x75, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x70, 0x63, 0x49,
	0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x70, 0x63, 0x49, 0x70, 0x12, 0x18,
	0x0a, 0x07, 0x69, 0x70, 0x63, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x69, 0x70, 0x63, 0x50, 0x6f, 0x72, 0x74, 0x32, 0x56, 0x0a, 0x0a, 0x49, 0x70, 0x63, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x48, 0x0a, 0x0c, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x74,
	0x75, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x12, 0x1c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x74, 0x75, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53,
	0x65, 0x6e, 0x64, 0x53, 0x74, 0x75, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x42, 0x1c, 0x5a, 0x1a, 0x67, 0x6f, 0x72, 0x6d, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x72, 0x70,
	0x63, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ipc_service_proto_rawDescOnce sync.Once
	file_ipc_service_proto_rawDescData = file_ipc_service_proto_rawDesc
)

func file_ipc_service_proto_rawDescGZIP() []byte {
	file_ipc_service_proto_rawDescOnce.Do(func() {
		file_ipc_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_ipc_service_proto_rawDescData)
	})
	return file_ipc_service_proto_rawDescData
}

var file_ipc_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ipc_service_proto_goTypes = []interface{}{
	(*SendStunAddrRequest)(nil), // 0: service.SendStunAddrRequest
	(*SendStunAddrReply)(nil),   // 1: service.SendStunAddrReply
}
var file_ipc_service_proto_depIdxs = []int32{
	0, // 0: service.IpcService.SendStunAddr:input_type -> service.SendStunAddrRequest
	1, // 1: service.IpcService.SendStunAddr:output_type -> service.SendStunAddrReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ipc_service_proto_init() }
func file_ipc_service_proto_init() {
	if File_ipc_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ipc_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendStunAddrRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ipc_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendStunAddrReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ipc_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ipc_service_proto_goTypes,
		DependencyIndexes: file_ipc_service_proto_depIdxs,
		MessageInfos:      file_ipc_service_proto_msgTypes,
	}.Build()
	File_ipc_service_proto = out.File
	file_ipc_service_proto_rawDesc = nil
	file_ipc_service_proto_goTypes = nil
	file_ipc_service_proto_depIdxs = nil
}
