// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.2
// source: ipc_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IpcServiceClient is the client API for IpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IpcServiceClient interface {
	SendStunAddr(ctx context.Context, in *SendStunAddrRequest, opts ...grpc.CallOption) (*SendStunAddrReply, error)
}

type ipcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIpcServiceClient(cc grpc.ClientConnInterface) IpcServiceClient {
	return &ipcServiceClient{cc}
}

func (c *ipcServiceClient) SendStunAddr(ctx context.Context, in *SendStunAddrRequest, opts ...grpc.CallOption) (*SendStunAddrReply, error) {
	out := new(SendStunAddrReply)
	err := c.cc.Invoke(ctx, "/service.IpcService/SendStunAddr", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IpcServiceServer is the server API for IpcService service.
// All implementations must embed UnimplementedIpcServiceServer
// for forward compatibility
type IpcServiceServer interface {
	SendStunAddr(context.Context, *SendStunAddrRequest) (*SendStunAddrReply, error)
	mustEmbedUnimplementedIpcServiceServer()
}

// UnimplementedIpcServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIpcServiceServer struct {
}

func (UnimplementedIpcServiceServer) SendStunAddr(context.Context, *SendStunAddrRequest) (*SendStunAddrReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendStunAddr not implemented")
}
func (UnimplementedIpcServiceServer) mustEmbedUnimplementedIpcServiceServer() {}

// UnsafeIpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IpcServiceServer will
// result in compilation errors.
type UnsafeIpcServiceServer interface {
	mustEmbedUnimplementedIpcServiceServer()
}

func RegisterIpcServiceServer(s grpc.ServiceRegistrar, srv IpcServiceServer) {
	s.RegisterService(&IpcService_ServiceDesc, srv)
}

func _IpcService_SendStunAddr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendStunAddrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IpcServiceServer).SendStunAddr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.IpcService/SendStunAddr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IpcServiceServer).SendStunAddr(ctx, req.(*SendStunAddrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IpcService_ServiceDesc is the grpc.ServiceDesc for IpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.IpcService",
	HandlerType: (*IpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendStunAddr",
			Handler:    _IpcService_SendStunAddr_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ipc_service.proto",
}
